#!/bin/sh
# NexOS git credential helper.
# Emits username/password from NEXOS_GIT_USERNAME / NEXOS_GIT_PASSWORD
# (or GIT_USERNAME / GIT_PASSWORD) as a git credential fill response.
echo "username=${NEXOS_GIT_USERNAME:-${GIT_USERNAME:-}}"
echo "password=${NEXOS_GIT_PASSWORD:-${GIT_PASSWORD:-}}"
